### ISSUE TITLE
Examples page titles should use the plural form + broken nav link for gadget snaps

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/developer.ubuntu.com#135]
1) On the main examples page, all links are using the plural form "See examples for hooks ›". Page titles on child pages should also use the plural form: "Hooks examples" instead of "Hook examples".

2) The "Gadget snaps" navigation item links to the "gadget-snaps" page, which doesn't exist. The current "gadget-snap.md" page should be renamed to "gadget-snaps.md"

**Comment by anasereijo** [comment]
@caldav is this still relevant?
