### ISSUE TITLE
Design anchor links on mobile (document and doc enhanced pages)

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#148]

**Comment by deadlight** [comment]
Does anyone know any detail about this issue?

**Comment by caldav** [comment]
Could be having a design for displaying a ToC (linking to titles on the page), such as the one top right of https://docs.ubuntu.com/core/en/guides/intro/security , that works on mobile.

**Comment by anthonydillon** [comment]
Closing this issue due to a lack of information.
