### ISSUE TITLE
[General] Cards on modular pages - reduce the bottom gap

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/developer.ubuntu.com#16]
Distance between "Resource" and the limits of the card should be 20px

**Comment by grahambancroft** [comment]
Fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus/examples/summary

**Comment by joanasa89** [comment]
The "Source" item should have the same bottom margin ("Ubuntu Core" is slightly up)

**Comment by grahambancroft** [comment]
Fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus/examples/summary
