### ISSUE TITLE
[General] Modular page - Add "external icon" on links & labels 

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/developer.ubuntu.com#17]

**Comment by grahambancroft** [comment]
Fixed on demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/summary

**Comment by joanasa89** [comment]
Labels and source should be in the light grey #666

**Comment by joanasa89** [comment]
External link icon: https://assets.ubuntu.com/v1/9334aabe-external-link-cool-grey.svg

**Comment by grahambancroft** [comment]
Changed on demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/summary

**Comment by grahambancroft** [comment]
Fixed on demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/summary

**Comment by ghost** [comment]
We need to double check with @yaili if we should go with vanilla or ubuntu style

**Comment by yaili** [comment]
This doesn't look right, if the demo is correct. The external links are too large.

**Comment by joanasa89** [comment]
@grahambancroft use the link's style from ubuntu. Use the same style as:
(for orange links) --> "Learn more about snaps" cta on https://www.ubuntu.com/core 
<img width="286" alt="screen shot 2016-12-06 at 15 04 58" src="https://cloud.githubusercontent.com/assets/21334617/20930477/60e71552-bbc5-11e6-96ae-2383e6ab5ed7.png">

(for label links) --> "LATEST NEWS FROM INSIGHTS" on https://www.ubuntu.com/
<img width="350" alt="screen shot 2016-12-06 at 15 04 52" src="https://cloud.githubusercontent.com/assets/21334617/20930478/60f9dec6-bbc5-11e6-8204-dfffc66ad9cf.png">


@grahambancroft Create a new request on vanilla framework.io to change this pattern.

**Comment by grahambancroft** [comment]
Changed on demo
