### ISSUE TITLE
Reword "develop on target"

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/developer.ubuntu.com#183]
"develop on target" means developing on your target device or board, as opposed to doing it on your workstation.

Is it obvious enough for a target audience of both seasoned IoT developers and beginners?

**Comment by nottrobin** [comment]
Should we just expand it to say "Develop on the target device"?

**Comment by nottrobin** [comment]
Mentioned in:

- [get-started](https://github.com/ubuntudesign/developer.ubuntu.com/tree/master/templates/pages/core/get-started/index.md)
- [developer setup](https://github.com/ubuntudesign/developer.ubuntu.com/tree/master/templates/pages/core/get-started/developer-setup.md)
- [get_started_first_boot include](https://github.com/ubuntudesign/developer.ubuntu.com/tree/master/templates/includes/markdown/get_started_first_boot.md)
