### ISSUE TITLE
Header height needs to be 48px

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/developer.ubuntu.com#198]
At the moment the header is 47px, should be 48 px to be consistent with the rest of the website

**Comment by WillMoggridge** [comment]
We should check with design, I think this refers to the main header bar on whole site which is 53px currently.

**Comment by deadlight** [comment]
developer.ubuntu.com's top nav is 53px, ubuntu.com's nav  - which developer is mimicking - is also 53px. This issue is no longer valid.
