### ISSUE TITLE
[Windows 10 / Edge] Documentation enhanced - buttons text has wrong colour

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#26]
When hovering over the arrows on side nav, the cursor doesn't change to indicate it's clickable

**Comment by grahambancroft** [comment]
Fixed on demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/documentation-enhanced

**Comment by grahambancroft** [comment]
Fixed on demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/documentation-enhanced
