### ISSUE TITLE
Double-redirection from https://developer.ubuntu.com

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/developer.ubuntu.com#271]
https://developer.ubuntu.com -> http://developer.ubuntu.com/en/ -> https://developer.ubuntu.com/en/. One step too many.

This is probably because Django isn't aware that it's served over HTTPS, so it initially responds with an HTTP redirect.

See https://design.canonical.com/2015/08/django-behind-a-proxy-fixing-absolute-urls/.

**Comment by nottrobin** [comment]
This may be an artifact of the old version of the site, and be fixed as soon as we go live properly with the new application.

**Comment by WillMoggridge** [comment]
This could potentially be fixed when we fully release the site, with our spec sending the correct header.
I have created PR #272 to correctly read the header.

This is likely from the old site but it is possibly from the squid cache, so we should check on this after release.

**Comment by anthonydillon** [comment]
This is no longer the case: 
```bash
$ wget https://developer.ubuntu.com
--2017-12-19 10:26:23--  https://developer.ubuntu.com/
Resolving developer.ubuntu.com (developer.ubuntu.com)... 91.189.89.246, 91.189.90.251
Connecting to developer.ubuntu.com (developer.ubuntu.com)|91.189.89.246|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
