### ISSUE TITLE
/pioneers has SSL proxy error

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-web-and-design/developer.ubuntu.com#286]
https://developer.ubuntu.com/pioneers has a proxy error relating to SSL

Looking at the config, this appears to be a mirror of https://myapps.developer.ubuntu.com/dev/click-apps/pioneers/
If this is the case, we should remove the apache config for it and redirect to that location with this app.

---

Originally reported by @rahulroopaljain
https://github.com/canonical-websites/www.ubuntu.com/issues/1800

**Comment by WillMoggridge** [comment]
@rahulroopaljain Would you be able to confirm it this is the site you are looking for:
https://myapps.developer.ubuntu.com/dev/click-apps/pioneers/

**Comment by rahulroopaljain** [comment]
@WillMoggridge, sorry for the delay in response, yes this is the site, but still seems like there is an issue, above mentioned pioneer portal supposed to have 200 individuals, whereas link which you provided above has only 20 in it. By any chance do you know why is it so?

**Comment by WillMoggridge** [comment]
@rahulroopaljain I am not sure why that is but thank you for pointing it out, I will raise the issue and see if we can locate the problem.

**Comment by rahulroopaljain** [comment]
@WillMoggridge did you raise separate issue for that? Or will it be tracked in same one?

**Comment by rahulroopaljain** [comment]
@WillMoggridge now https://developer.ubuntu.com/pioneers is up and running.. Thanks for that... is there anyone looking into issue related to less content displayed on that pioneer portal? I mean instead of 200 individuals only 20 are visible, as I mentioned above.

**Comment by rahulroopaljain** [comment]
Hi @WillMoggridge any update on this? I can still see only 20 members whereas it supposed to be 200 pioneers in that web portal.

**Comment by rahulroopaljain** [comment]
I have created new issue for this https://github.com/canonical-websites/developer.ubuntu.com/issues/327

**Comment by anasereijo** [comment]
@nottrobin is this still something we can/should do?
