### ISSUE TITLE
The API website is missing

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/developer.ubuntu.com#292]
https://developer.ubuntu.com/api has been missing since the last deployment. It should be online in some form, to complement the content available at https://docs.ubuntu.com/phone/en/

**Comment by nottrobin** [comment]
What used to be at that location? Is it in any way covered under https://docs.ubuntu.com/phone/en/scopes/index ?

@pmahnke what's your feeling about this one?

**Comment by pmahnke** [comment]
I ported all the current and developement api's into the docs

[API - autopilot (current)](https://docs.ubuntu.com/phone/en/apps/api-autopilot-current/index)
[API - autopilot (development)](https://docs.ubuntu.com/phone/en/apps/api-autopilot-development/index)
[API - html5 (current)](https://docs.ubuntu.com/phone/en/apps/api-html5-current/index)
[API - html5 (development)](https://docs.ubuntu.com/phone/en/apps/api-html5-development/index)
[API - qml (current)](https://docs.ubuntu.com/phone/en/apps/api-qml-current/index)
[API - qml (development)](https://docs.ubuntu.com/phone/en/apps/api-qml-development/index)
[API - C++ (current)](https://docs.ubuntu.com/phone/en/scopes/api-cpp-current/index)
[API - C++ (development)](https://docs.ubuntu.com/phone/en/scopes/api-cpp-development/index)
[API - Javascript (current)](https://docs.ubuntu.com/phone/en/scopes/api-js-current/index)
[API - Javascript (development)](https://docs.ubuntu.com/phone/en/scopes/api-js-development/index)

took AGES

**Comment by ghost** [comment]
We agreed to redirect to: https://docs.ubuntu.com/phone/en/ since all of these pages can be found there
