### ISSUE TITLE
[Small screen] - Tutorial page - Remove bullet points from"what,how,where" and fix space between them

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/developer.ubuntu.com#31]

**Comment by grahambancroft** [comment]
Fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus/examples/tutorials

**Comment by joanasa89** [comment]
Can we add top-margin on "when" and "how"? (around 20-30px)
<img width="396" alt="screen shot 2016-11-30 at 14 15 21" src="https://cloud.githubusercontent.com/assets/21334617/20755613/79c62a80-b707-11e6-8dab-d539a1167a33.png">

**Comment by grahambancroft** [comment]
Fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus/examples/tutorials

**Comment by jamiedawsonyoung** [comment]
Hey, so there is something weird looking but I've discussed with @grahambancroft and it's a core Vanilla styling problem. We need to file a bug against Vanilla to get this fixed rather than hack this.
