### ISSUE TITLE
Snapcraft page: "Latest Tutorials" section failing to load feed

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#317]
At https://developer.ubuntu.com/snapcraft, section "Latest Tutorials" shows "Feed failed to load."

![feedfailedtoload](https://user-images.githubusercontent.com/12199980/31231837-4be88f5c-a9e8-11e7-8382-d0cc5ae3463e.png)

**Comment by anthonydillon** [comment]
Thank you very much for the heads up @sanjacloud. We will get a fix for this as soon as possible.
