### ISSUE TITLE
[Mac / Safari] Button hover state issue

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#32]
Documentation enhanced page

on hover, button gets orange bottom border / shadow (see screengrab attached)
![screen shot 2016-11-28 at 15 34 54](https://cloud.githubusercontent.com/assets/16683435/20674323/6386a05c-b580-11e6-92ec-172308e9025d.png)

**Comment by grahambancroft** [comment]
Fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus/openid-auth/+login
