### ISSUE TITLE
Offline catalog/repository required additional files in Ubuntu 16.04

### ISSUE THREAD

**Issue by shubhendu-kumar** [canonical-web-and-design/developer.ubuntu.com#328]
Till Ubuntu 14.04, I used to create offline repository for analysis i.e. apt-get update and later based on my requirement I will install required packages. In Ubuntu 14.04 I only required Packages.gz file but after migrating to Ubuntu 16.04 the same script is ask for "InRelease" files under SuiteCodename and "Translation-en.gz" under <component>/i18n directories.
1. Could someone help me to understand why these additional files are required?
2. Is there any way to disable these additional files? If "YES", how?

**Comment by anthonydillon** [comment]
Hello @shubhendu-kumar.

Sorry to hear you are having a problem with Ubuntu. Unfortunately I cannot provide support via this channel as I am a member of the web team.

If you could report an bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question on askubuntu.com you should receive a quick response.
