### ISSUE TITLE
unable to locate package issue

### ISSUE THREAD

**Issue by bhaski-1234** [canonical-web-and-design/developer.ubuntu.com#329]
yesterday i installed ubuntu on my pc and i though to install some softwares as chromium and many more.but when i opened terminal and made this command
$ sudo apt-get install <package>
reading package lists...done
building dependency tree
reading state information... done
E:unable to locate package <package>
i use to get this error.
i tried every thing which i found on internet nothing worked.everything i mean everything available on youtube or some blogs or stackexchange or askubuntu or many more.please help me in fixing this problem

**Comment by anthonydillon** [comment]
Hello @bhaski-1234.

Sorry to hear you are having a problem with apt-get. Unfortunately I cannot provide support via this channel as I am a member of the web team.

If you could report an bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question on askubuntu.com you should receive a quick response.
