### ISSUE TITLE
core/troubleshooting page directs to Ask Ubuntu instead of forum.snapcraft.io

### ISSUE THREAD

**Issue by alextnewman** [canonical-web-and-design/developer.ubuntu.com#332]
If I navigate to https://developer.ubuntu.com/core/troubleshooting I'm told I should be looking to Ask Ubuntu first for guidance. We should be directing users to forum.snapcraft.io and probably making no mention of Ask Ubuntu.

**Comment by anthonydillon** [comment]
Thank you for this update. We will update this shortly.

**Comment by pmahnke** [comment]
closing
