### ISSUE TITLE
remove fixed checksum from https://developer.ubuntu.com/core/get-started/compute-module-3

### ISSUE THREAD

**Issue by vorlonofportland** [canonical-web-and-design/developer.ubuntu.com#334]
https://developer.ubuntu.com/core/get-started/compute-module-3 lists a sha256 for the cm image download.  This is inconsistent with the other pages, and the checksum is subject to change at any point due to updates of the images.

We are updating images today, so this checksum is expected to become invalid imminently.

Please remove the sha256 from this page.  If we want to provide users a way to validate checksums of ubuntu-core downloads, they should be pointed at http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/SHA256SUMS and http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/SHA256SUMS.gpg

**Comment by anthonydillon** [comment]
This issue was resolved in the linked issue.
