### ISSUE TITLE
landing page "Latest Tutorials" says "Feed failed to load"

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/developer.ubuntu.com#345]
The landing page at developer.ubuntu.com has a section at the bottom titled "Latest Tutorials".

It currently has an error that says:

"Feed failed to load. If you have time, please file an issue."

So here I am, filing an issue :)

**Comment by Lukewh** [comment]
Duplicate of https://github.com/canonical-websites/developer.ubuntu.com/issues/331. Thanks for the report
