### ISSUE TITLE
Link for SeedManagement on Ubuntu Wiki generates Internal Server Error

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/developer.ubuntu.com#347]
A Google Search for "ubuntu server seed"
https://www.google.com/search?q=ubuntu+server+seed&oq=ubuntu+server+seed

returns this link as the top result:
https://wiki.ubuntu.com/SeedManagement

SeedManagement - Ubuntu Wiki
https://wiki.ubuntu.com/SeedManagement
Apr 28, 2005 - Standard. The standard system provides a solid foundation for a desktop or server without providing X11 or any services listening on any non-localhost ports. This seed package list, once the complete dependency set has been added, provides that system. The criteria for packages in standard are similar to ...
‎Minimal · ‎Standard · ‎Desktop · ‎Supported

However, when I click on that link, I get an "Internal Server Error" instead:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@ubuntu.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.'

Other links (internal links) on wiki.ubuntu.com are also failing, such as:

https://wiki.ubuntu.com/Social
https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes
https://wiki.ubuntu.com/XenialXerus/ReleaseNotes/ChangeSummary/16.04.1
https://wiki.ubuntu.com/XenialXerus

Interestingly, these DID work:
https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes
https://wiki.ubuntu.com/Releases

**Comment by caldav** [comment]
Thanks for the heads up, all these pages seem to be working again today, I suspect a temporary issue on the wiki. Please reopen the issue if it's still relevant to you.
