### ISSUE TITLE
404 error for ubuntu 15.4 sudo apt-get update hitting 

### ISSUE THREAD

**Issue by narayanchonde** [canonical-web-and-design/developer.ubuntu.com#348]
Hit http://packages.microsoft.com stable InRelease
Ign http://in.archive.ubuntu.com vivid InRelease                                             
Hit http://ppa.launchpad.net vivid InRelease                                                 
Get:1 http://packages.microsoft.com stable/main amd64 Packages [40.5 kB]                                
Ign http://in.archive.ubuntu.com vivid-updates InRelease                                                
Ign http://security.ubuntu.com vivid-security InRelease                                          
Ign http://in.archive.ubuntu.com vivid Release.gpg                                                      
Get:2 http://ppa.launchpad.net vivid InRelease [15.4 kB]                                                
Ign http://security.ubuntu.com vivid-security Release.gpg                                              
Ign http://in.archive.ubuntu.com vivid-updates Release.gpg                                             
Ign http://ppa.launchpad.net vivid InRelease                                                            
Ign http://in.archive.ubuntu.com vivid Release                                                          
Ign http://security.ubuntu.com vivid-security Release                                                   
Ign http://in.archive.ubuntu.com vivid-updates Release                                           
Ign http://ppa.launchpad.net vivid InRelease                                                     
Ign http://security.ubuntu.com vivid-security/main Sources/DiffIndex  
Ign http://in.archive.ubuntu.com vivid/main Sources/DiffIndex                                    
Ign http://packages.microsoft.com stable/main Translation-en_IN                                  
Ign http://packages.microsoft.com stable/main Translation-en                                     
Ign http://in.archive.ubuntu.com vivid/restricted Sources/DiffIndex                              
Ign http://security.ubuntu.com vivid-security/restricted Sources/DiffIndex
Hit http://ppa.launchpad.net vivid InRelease    
Ign http://in.archive.ubuntu.com vivid/universe Sources/DiffIndex                                       
Ign http://security.ubuntu.com vivid-security/universe Sources/DiffIndex                         
Ign http://in.archive.ubuntu.com vivid/multiverse Sources/DiffIndex        
Ign http://in.archive.ubuntu.com vivid/main amd64 Packages/DiffIndex
Ign http://security.ubuntu.com vivid-security/multiverse Sources/DiffIndex 
Ign http://in.archive.ubuntu.com vivid/restricted amd64 Packages/DiffIndex 
Ign http://security.ubuntu.com vivid-security/main amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid/universe amd64 Packages/DiffIndex                         
Ign http://in.archive.ubuntu.com vivid/multiverse amd64 Packages/DiffIndex                       
Ign http://security.ubuntu.com vivid-security/restricted amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid/main i386 Packages/DiffIndex
Ign http://security.ubuntu.com vivid-security/universe amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid/restricted i386 Packages/DiffIndex  
Ign http://ppa.launchpad.net vivid/main amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid/universe i386 Packages/DiffIndex
Ign http://security.ubuntu.com vivid-security/multiverse amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid/multiverse i386 Packages/DiffIndex  
Ign http://security.ubuntu.com vivid-security/main i386 Packages/DiffIndex 
Ign http://ppa.launchpad.net vivid/main i386 Packages/DiffIndex
Ign http://security.ubuntu.com vivid-security/restricted i386 Packages/DiffIndex                 
Ign http://security.ubuntu.com vivid-security/universe i386 Packages/DiffIndex                   
Ign http://security.ubuntu.com vivid-security/multiverse i386 Packages/DiffIndex
Hit http://ppa.launchpad.net vivid Release.gpg                             
Ign http://in.archive.ubuntu.com vivid-updates/main Sources/DiffIndex      
Ign http://in.archive.ubuntu.com vivid-updates/restricted Sources/DiffIndex
Ign http://in.archive.ubuntu.com vivid-updates/universe Sources/DiffIndex  
Ign http://in.archive.ubuntu.com vivid-updates/multiverse Sources/DiffIndex                      
Hit http://ppa.launchpad.net vivid/main amd64 Packages                                           
Ign http://in.archive.ubuntu.com vivid-updates/main amd64 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid-updates/restricted amd64 Packages/DiffIndex                      
Hit http://ppa.launchpad.net vivid/main i386 Packages                                            
Ign http://in.archive.ubuntu.com vivid-updates/universe amd64 Packages/DiffIndex                        
Ign http://in.archive.ubuntu.com vivid-updates/multiverse amd64 Packages/DiffIndex                      
Hit http://ppa.launchpad.net vivid/main Translation-en                                           
Ign http://in.archive.ubuntu.com vivid-updates/main i386 Packages/DiffIndex                             
Ign http://in.archive.ubuntu.com vivid-updates/restricted i386 Packages/DiffIndex                
Ign http://in.archive.ubuntu.com vivid-updates/universe i386 Packages/DiffIndex
Ign http://in.archive.ubuntu.com vivid-updates/multiverse i386 Packages/DiffIndex                       
Hit http://ppa.launchpad.net vivid/main Translation-en                                                  
Hit http://ppa.launchpad.net vivid Release                                                              
Hit http://ppa.launchpad.net vivid/main amd64 Packages                                                                                           
Hit http://ppa.launchpad.net vivid/main i386 Packages                                                                                            
Hit http://ppa.launchpad.net vivid/main Translation-en                                                                                           
Hit http://ppa.launchpad.net vivid/main amd64 Packages                                                                                           
Hit http://ppa.launchpad.net vivid/main i386 Packages                                                                                            
Hit http://ppa.launchpad.net vivid/main amd64 Packages                                                                                           
Hit http://ppa.launchpad.net vivid/main i386 Packages                                                                                            
Hit http://ppa.launchpad.net vivid/main Translation-en                                                                                           
Ign http://ppa.launchpad.net vivid/main Translation-en_IN                                                                                        
Ign http://security.ubuntu.com vivid-security/main Translation-en_IN                                                                             
Ign http://security.ubuntu.com vivid-security/main Translation-en
Ign http://security.ubuntu.com vivid-security/multiverse Translation-en_IN
Ign http://security.ubuntu.com vivid-security/multiverse Translation-en
Ign http://security.ubuntu.com vivid-security/restricted Translation-en_IN
Ign http://security.ubuntu.com vivid-security/restricted Translation-en
Ign http://security.ubuntu.com vivid-security/universe Translation-en_IN
Ign http://security.ubuntu.com vivid-security/universe Translation-en
Err http://security.ubuntu.com vivid-security/main Sources
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/restricted Sources
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/universe Sources
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/multiverse Sources
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/main amd64 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/restricted amd64 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/universe amd64 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/multiverse amd64 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/main i386 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/restricted i386 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/universe i386 Packages
  404  Not Found [IP: 91.189.91.23 80]
Err http://security.ubuntu.com vivid-security/multiverse i386 Packages
  404  Not Found [IP: 91.189.91.23 80]
Ign http://in.archive.ubuntu.com vivid/main Translation-en_IN
Ign http://in.archive.ubuntu.com vivid/main Translation-en
Ign http://in.archive.ubuntu.com vivid/multiverse Translation-en_IN
Ign http://in.archive.ubuntu.com vivid/multiverse Translation-en
Ign http://in.archive.ubuntu.com vivid/restricted Translation-en_IN
Ign http://in.archive.ubuntu.com vivid/restricted Translation-en
Ign http://in.archive.ubuntu.com vivid/universe Translation-en_IN
Ign http://in.archive.ubuntu.com vivid/universe Translation-en
Ign http://in.archive.ubuntu.com vivid-updates/main Translation-en_IN
Ign http://in.archive.ubuntu.com vivid-updates/main Translation-en
Ign http://in.archive.ubuntu.com vivid-updates/multiverse Translation-en_IN
Ign http://in.archive.ubuntu.com vivid-updates/multiverse Translation-en
Ign http://in.archive.ubuntu.com vivid-updates/restricted Translation-en_IN
Ign http://in.archive.ubuntu.com vivid-updates/restricted Translation-en
Ign http://in.archive.ubuntu.com vivid-updates/universe Translation-en_IN
Ign http://in.archive.ubuntu.com vivid-updates/universe Translation-en
Err http://in.archive.ubuntu.com vivid/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/universe Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/multiverse Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/main amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/universe amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/multiverse amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/main i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/restricted i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/universe i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/universe Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/multiverse Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/main amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/universe amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/multiverse amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/main i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/restricted i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/universe i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://in.archive.ubuntu.com vivid-updates/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Fetched 15.4 kB in 37s (406 B/s)
W: GPG error: http://ppa.launchpad.net vivid InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A1715D88E1DF1F24
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/main/source/Sources  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/main/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/restricted/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/restricted/source/Sources  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/universe/source/Sources  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/multiverse/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/multiverse/source/Sources  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/vivid-security/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/main/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/restricted/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/multiverse/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/vivid-updates/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80

**Comment by caldav** [comment]
Hello, you may want to know that 15.04 has reached End of Life [2 years ago](http://fridge.ubuntu.com/2016/01/14/ubuntu-15-04-vivid-vervet-reaches-end-of-life-on-february-4-2016/), which is why you are getting these errors. I advise you to look at the list of [currently supported releases](https://wiki.ubuntu.com/Releases) and update your installation to one of them to get security fixes.
