### ISSUE TITLE
[ipad portrait] navigation issue

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#35]
Half of the top navigation goes light grey - see screengrab
![img_0416](https://cloud.githubusercontent.com/assets/16683435/20719372/9cd0b34c-b653-11e6-9ff8-3a40cc403fba.PNG)

**Comment by grahambancroft** [comment]
Fixed on demo http://developer.ubuntu.com-add-template-code.demo.haus/
