### ISSUE TITLE
“Access your Debian or click packages” goes to the wrong place

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/developer.ubuntu.com#360]
1\. Go to the “[Community resources](https://developer.ubuntu.com/community-resources)” page.
2\. Follow the link, “If you have an existing Debian or phone app in the store and would like to access your dashboard, [visit My Apps](https://myapps.developer.ubuntu.com/)”.

What happens: You end up at [snapcraft.io/](https://snapcraft.io/), with no mention of Debian or phone apps or even a developer account.

What should happen: either
- that section no longer exists, or
- the link goes to the correct site.

**Comment by nottrobin** [comment]
Thanks @matthewpaulthomas.

developer.ubuntu.com and this project will be retired imminently, and all URLs on developer.ubuntu.com will be redirected elsewhere. Specifically, https://developer.ubuntu.com/community-resources will be redirected to https://forum.snapcraft.io.

At that point I believe this will no longer be an issue, so I'm going to close this issue. If you still feel there's an issue with the communication of community resources the best place to bring it up would probably be on the snapcraft forum.
