### ISSUE TITLE
How to copy Ubuntu Core image? How to prepare USB flash drive

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [canonical-web-and-design/developer.ubuntu.com#364]
On https://developer.ubuntu.com/core/get-started/intel-nuc

The instructions for preparing a USB Flash Drive for Ubuntu Desktop are very nice. However the instructions for preparing a USB Flash Drive for the Ubuntu Core image are lacking:
```
Prepare installation medias
Download and copy the Ubuntu Desktop 16.04.1 LTS image on the first USB flash drive by following the Live USB Ubuntu Desktop instuctions for Ubuntu | Windows | Mac OS X
Download the Ubuntu Core image for Intel NUC and copy the file on the second USB flash drive
```

Is it just, format the drive as FAT and copy the .xy file over? Later instructions include how to copy the file from the USB flash drive to the new system.

**Comment by pmahnke** [comment]
@drjasonharrison-vp-eio the developer.u.c site is a bit out of date.  Perhaps https://www.ubuntu.com/download/iot is a better resource?

**Comment by drjasonharrison-vp-eio** [comment]
Thanks
