### ISSUE TITLE
Version Changed ????

### ISSUE THREAD

**Issue by nikkpap** [canonical-web-and-design/developer.ubuntu.com#370]
change this link
from 
http://cdimage.ubuntu.com/ubuntu/releases/16.04/release/ubuntu-16.04-preinstalled-server-armhf+raspi2.img.xz

to 
http://cdimage.ubuntu.com/ubuntu/releases/16.04/release/ubuntu-16.04.4-preinstalled-server-armhf+raspi2.img.xz

it has been updated and not found on server the old img

thanks

**Comment by anthonydillon** [comment]
@nikkpap Thank you for reporting an issue. I am having trouble finding this link to update. The latest downloads are to `18.04.2`:
https://www.ubuntu.com/download/iot/raspberry-pi-2-3

If this is still an issue please reopen and share the link which is wrong.
