### ISSUE TITLE
"View your snaps in snapcraft.io" is white on hover

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/developer.ubuntu.com#398]
If I hover over the "View your snaps in snapcraft.io" link in the top right, it looks like this (in Chromium 69.0.3497.81, non-snap version, Ubuntu 18.04):

![screenshot from 2019-01-14 11-55-59](https://user-images.githubusercontent.com/519935/51111328-a5f06e00-17f3-11e9-838f-4bfafd23cc51.png)

Which is ugly as sin. Should be fixed.

**Comment by anasereijo** [comment]
@solazio please remove the white background and keep the underline text as hover state.

**Comment by nottrobin** [comment]
@pmahnke - is this worth doing? realistically, how long will developer.ubuntu.com stick around?
