### ISSUE TITLE
Snappy Ubuntu Core images for Raspberry Pi 3 are armv7l

### ISSUE THREAD

**Issue by sixcorners** [canonical-web-and-design/developer.ubuntu.com#412]
https://developer.ubuntu.com/core/get-started/raspberry-pi-2-3
This page should probably warn or give some notice that the raspberry pi 3 image is not aarch64.

**Comment by nottrobin** [comment]
Thanks @sixcorners. This project is being archived and https://developer.ubuntu.com URLs will be redirected elsewhere.

The URL you cite - https://developer.ubuntu.com/core/get-started/raspberry-pi-2-3 - already redirects to https://www.ubuntu.com/download/iot/raspberry-pi-2-3. If you consider this issue to still be relevant to that new page, please could you file the issue again over at https://github.com/canonical-web-and-design/www.ubuntu.com/issues ?

Thanks again.
