### ISSUE TITLE
[General] Side navigation - spacing between items

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#8]
Review the spacing as per attached design

**Comment by joanasa89** [comment]
![native apps - get started](https://cloud.githubusercontent.com/assets/21334617/20603736/c500dfd8-b25a-11e6-8013-914d62b0ff08.png)

**Comment by grahambancroft** [comment]
Fixed on the demo http://developer.ubuntu.com-add-template-code.demo.haus/examples/documentation-enhanced
